### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by smuaq** [apizee/ApiRTC-mobile#1]
Thanks for the plugin, when are you planning to release Android support?

**Comment by FredLuart** [comment]
This sample is for iOS only, for android you can follow our tutorial on www.apirtc.com : https://apirtc.com/apirtc-on-cordova/

**Comment by smuaq** [comment]
I tried that tutorial for android (version 5). Followed all the steps, the connection is also established (https://cloud.apizee.com/apiRTC/Samples/apiPhone-level2.html) but as soon as that is done my mobile application completely freezes. Any idea how to go about that? Thanks.

**Comment by smuaq** [comment]
Got it to work. It was a permission issue with Android 6, had to use target sdk 22.

**Comment by sliard** [comment]
thx @smuaq we update this sample for android and with a solution for Android 6 permissions :)

**Comment by smuaq** [comment]
Welcome 💯
