### ISSUE TITLE
some users always get contacted state

### ISSUE THREAD

**Issue by AmrAlmagic** [apizee/ApiRTC-mobile#11]
I use your library with ionic 3 and works well. 
I get call state info for users already online but some users always get contacted as his/her state !!.
 Every user has a unique code associated with apirtc in initialization.

I tried to get a call state for each online user.

I use this code to get call state for each online user according to this [reference](https://dev.apirtc.com/apiRTC_V3/module-ApiRTCSession.html#~getConnectedUserInfo__anchor)

```
  getConnectedDoctorInfo(userCode: String) {
    return apiRTC.session.getConnectedUserInfo(`${userCode}`, 'callState');
  }
```
but some users always get contacted state instead of no_call state !

**Comment by FredLuart** [comment]
Closing the issue as it is corrected
