### ISSUE TITLE
WkWebView and iosrtc plugin compatibility

### ISSUE THREAD

**Issue by Giap3268** [apizee/ApiRTC-mobile#16]
According with new Apple diktat, we need to use WkWebView, so we are experimenting the [cordova-plugin-wkwebview-engine](https://github.com/apache/cordova-plugin-wkwebview-engine) plugin, like this blog post suggests:

https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html

Is this plugin compatible with ApiRTC-mobile cordova implementation (essentially with cordova-plugin-iosrtc)? 
We need to accomplish any modification to your code example?

**Comment by sachakh** [comment]
no info for now, need to investigate

**Comment by Giap3268** [comment]
Hi, we need to upgrade our iOS version of ApiRTC mobile with cordova-plugin-wkwebview-engine plugin, but we are unable to get a good implementation. 
Without your help we are in stuck.
Please, give us some feedback

**Comment by sachakh** [comment]
Hi @Giap3268, WKWebView is default web view on cordova-ios 6+:

>Due to this change, the cordova-plugin-wkwebview-engine plugin is obsolete and will not work with this release. If you have this plugin installed, it is safe to remove with cordova plugin remove cordova-plugin-wkwebview-engine.
https://cordova.apache.org/announcements/2020/06/01/cordova-ios-release-6.0.0.html
