### ISSUE TITLE
iOS problem with media devices

### ISSUE THREAD

**Issue by Giap3268** [apizee/ApiRTC-mobile#17]
I'm experimenting some trouble with ApiRTC implementation for Cordova.
My environment settings:
cordova-ios 6.1.0
iPad with iOS 14.1
Xcode 12.3
apirtc 4.4.6

The error registered in log is:
[Info] Loading APIRTC_MODULE (apiRTC-4.4.6.min.js, line 2)
[Warning] [2021-01-12T17:24:58.010Z][WARN]apiRTC(MediaDeviceManager) – "Media detection is not supported by browser, considering micro and camera present" (apiRTC-4.4.6.min.js, line 2)
[Error] TypeError: undefined is not an object (evaluating 'navigator.mediaDevices.getDisplayMedia')
	(funzione anonima) (apiRTC-4.4.6.min.js:2:1014319)
	(funzione anonima) (apiRTC-4.4.6.min.js:2:450794)
	(funzione anonima) (apiRTC-4.4.6.min.js:2:450819)
	i (apiRTC-4.4.6.min.js:2:115)
	(funzione anonima) (apiRTC-4.4.6.min.js:2:398633)
	i (apiRTC-4.4.6.min.js:2:115)
	(funzione anonima) (apiRTC-4.4.6.min.js:2:904)
	Codice globale (apiRTC-4.4.6.min.js:2:914)

Plugins in config.xml:
    <plugin name="cordova-plugin-device" spec="^2.0.3" />
    <plugin name="cordova-plugin-media" spec="^5.0.3" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.4" />
    <plugin name="cordova-plugin-iosrtc" spec="^6.0.16" />
    <plugin name="cordova-plugin-audioinput" spec="^1.0.2" />
    <plugin name="cordova-plugin-dialogs" spec="^2.0.2" />
    <plugin name="cordova-plugin-statusbar" spec="^2.4.3" />
    <plugin name="cordova-plugin-background-mode" spec="^0.7.3" />
    <plugin name="cordova-plugin-file" spec="^6.0.1" />
    <plugin name="cordova-plugin-camera" spec="~5.0.1">
        <variable name="CAMERA_USAGE_DESCRIPTION" value=" " />
        <variable name="PHOTOLIBRARY_USAGE_DESCRIPTION" value=" " />
    </plugin>
    <plugin name="cordova-plugin-network-information" spec="^2.0.2" />
    <plugin name="cordova-plugin-audioroute" spec="^0.1.2" />
    <plugin name="cordova-plugin-insomnia" spec="^4.3.0" />
    <plugin name="com.dooble.audiotoggle" spec="file:custom-plugins/audiotoggle" />
    <plugin name="phonegap-plugin-push" spec="~2.3.0" />
    <plugin name="cordova-plugin-facebook4" spec="6.4.0">
        <variable name="APP_ID" value="000000000" />
        <variable name="APP_NAME" value="byname" />
        <variable name="FACEBOOK_HYBRID_APP_EVENTS" value="true" />
        <variable name="FACEBOOK_ANDROID_SDK_VERSION" value="5.13.0" />
    </plugin>
    <plugin name="cordova-plugin-inappbrowser" spec="~4.1.0" />
	<plugin name="cordova-plugin-media-capture" spec="~3.0.3" />

**Comment by sachakh** [comment]
Is it issue with this repo? If you use a custom implementation please contact with Apizee support https://www.apizee.com/fr/faq-et-support/
