### ISSUE TITLE
ApiRTC initialization error

### ISSUE THREAD

**Issue by Giap3268** [apizee/ApiRTC-mobile#18]
With iOS implementation I'm experimenting the follow issue:

[Error] [2021-01-12T17:24:59.692Z][ERROR]apiRTC(UserAgent) – "register() - ApiRTC Initialization error : ReferenceError: Can't find variable: apiRTC_sioLoader"
	(funzione anonima) (videochat_app.js:55)
	(funzione anonima) (cordova.js:1413)
	value (apiRTC-4.4.6.min.js:2:19431)
	value (apiRTC-4.4.6.min.js:2:18980)
	createError (apiRTC-4.4.6.min.js:2:8929)
	(funzione anonima) (apiRTC-4.4.6.min.js:2:366738)
	promiseReactionJob
[Error] User agent registration failed – {code: 5, error: Error: register() - ApiRTC Initialization error : ReferenceError: Can't find variable: apiRTC_sioLoa…}
{code: 5, error: Error: register() - ApiRTC Initialization error : ReferenceError: Can't find variable: apiRTC_sioLoa…}Object
	(funzione anonima) (videochat_app.js:55)
	(funzione anonima) (cordova.js:1413)
	(funzione anonima) (videochat_app.js:1174)
	promiseReactionJob

My environment is:
Xcode 12.3
Cordova-ios 6.1.0
apiRTC 4.4.6
iPad iOS 14.1

**Comment by sachakh** [comment]
Can't reproduce this issue on iPad. Could you provide code sample?
