### ISSUE TITLE
Authentication Process using JSON Token Not Working

### ISSUE THREAD

**Issue by creativitycomkw** [apizee/ApiRTC-mobile#19]
Hi,

I am facing an issue with the Authentication Process using JSON Token
after generating the token, it only works only once or not even once and we get the registration error
please check this issue and take necessary action on it

**Comment by FredLuart** [comment]
Please make sure not to change your configuration on authentication activation : there is a 10 mn cache on the enterprise configuration : I think it may explain the behavior

**Comment by creativitycomkw** [comment]
ok you mean to say, I have to wait for a minimum of 10 mins to get changes to reflect?

**Comment by FredLuart** [comment]
Yes, when you change the authentication configuration on the dashboard

**Comment by creativitycomkw** [comment]
ok got it

**Comment by FredLuart** [comment]
I am closing the issue as I suppose this is ok

**Comment by creativitycomkw** [comment]
Hi,

I am still facing the same issue
after waiting for half an hour the authentication configuration is not getting refreshed on the server

kindly check the attached screenshot

<img width="1257" alt="Screen Shot 2021-01-14 at 9 46 38 AM" src="https://user-images.githubusercontent.com/66077942/104554802-ce630b00-564d-11eb-8c7f-37859e43107b.png">

**Comment by FredLuart** [comment]
JWT malformed mean that the token your are using for registration is not correct : it doesn't pass the verify() checking of JWT

Check documentation here : https://dev.apirtc.com/authentication
and here for token generation : https://apirtc.com/apirtc-access-token-using-json-web-token-jwt-for-session-authentication/

**Comment by creativitycomkw** [comment]
ok but I am copying the token from the panel and using it in the app
I tried so many times
I am sure it is not a typo mistake
it never worked with me

**Comment by FredLuart** [comment]
Are you not talking about the secret key instead of the token ? 

You need to generate the token with the code : https://github.com/apizee/apiRTC_JSON_Token_generator

The secret key, you have in the dashboard is then used to generate the token

**Comment by creativitycomkw** [comment]
ok got it
