### ISSUE TITLE
Symbol not found in iOS 8.4

### ISSUE THREAD

**Issue by impactotecnologico** [apizee/ApiRTC-mobile#2]
I have an error running this example.

My environment:
XCode 8.3.3
Target iOS: 8.4
iPhone 5 - iOS 8.4

Xcode Console error:
dyld: Symbol not found: ___NSDictionary0__
  Referenced from: /private/var/mobile/Containers/Bundle/Application/DDA22B4F-7EDC-4B02-B966-973ED018F94F/HelloRTC.app/HelloRTC
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 in /private/var/mobile/Containers/Bundle/Application/DDA22B4F-7EDC-4B02-B966-973ED018F94F/HelloRTC.app/HelloRTC

Steps:
Follow all steps of: https://github.com/apizee/ApiRTC-mobile 
console command:  ionic build ios --prod
Xcode: Open platforms/ios/HelloRTC.xcworkspace
Select device
Run

Any clue to fix it?

**Comment by sliard** [comment]
Hi,

Our library is base on [iosrtc Cordova plugin](https://github.com/BasqueVoIPMafia/cordova-plugin-iosrtc).
And it need at least iOS 9.

Do not forget to launch init.sh to get all required plugin.

Samuel

**Comment by impactotecnologico** [comment]
Thanks!
