### ISSUE TITLE
video doesn't show in device 

### ISSUE THREAD

**Issue by bolahanna44** [apizee/ApiRTC-mobile#3]
i installed all the plugins and cloned the repo but when i run 
cordova run android to test in virtual machine using 
nexus 5x API 24 

i can't see the camera of other peer neither am i  but i can see the video of both peers in desktop computer  ???

**Comment by bolahanna44** [comment]
i managed to fix this installing crosswalk plugin

**Comment by sliard** [comment]
Ok perfect :)
Crosswalk is mandatory for android before version 5.
