### ISSUE TITLE
hangup button on video stream

### ISSUE THREAD

**Issue by scorpianking007** [apizee/ApiRTC-mobile#4]
Hi Guys, I am developing IOS APP. I clone your repo its working good I have set video stream as full screen on IOS device it also works perfect but I tried to place hangup button on top of video stream the button dont show on the top of video stream. I play with z-index but z-index dont work  . My same code work perfect on android
how can i place it. any advice ?
thanks in advance

**Comment by FredLuart** [comment]
Hi, this is restriction that is coming from the iosRTC plugin on cordova
