### ISSUE TITLE
Audio should be played via earpiece by default

### ISSUE THREAD

**Issue by oriongunning** [apizee/ApiRTC-mobile#6]
Anyway to switch or toggle audio from earpiece to speaker? 

PS: Btw, it's amazing how well your API is working, I'm get fluid video chat from OZ to CHINA, and vice versa.

**Comment by francois-legoff** [comment]
Hi, we use cordova plugin https://github.com/alongubkin/audiotoggle to switch between earpiece or speaker mode

**Comment by oriongunning** [comment]
Thanks . I got it to work. 

For anybody who is struggling to get it to work, you have to wait to the call is ongoing before toggling the sound.
