### ISSUE TITLE
The SSL certificate used to load resources from https://cloud.apizee.com will be distrusted in M70

### ISSUE THREAD

**Issue by oriongunning** [apizee/ApiRTC-mobile#7]
The SSL certificate used to load resources from https://cloud.apizee.com will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

**Comment by FredLuart** [comment]
Hello,
We have already contacted our SSL provider for this issue that will only have an impact on October 2018. Our SSL certificate will be renewed before this date.
