### ISSUE TITLE
Remote video not recived when is not connected to wifi

### ISSUE THREAD

**Issue by RitaRoca** [apizee/ApiRTC-mobile#9]
Hi, I found another problem. I clone that project and tested in a real on android 6.0.

When I use the real device with no a wifi connection (3G, 4G) the remote video is not recived, it dont appear anthing.

Any solution?

**Comment by FredLuart** [comment]
Do you still have the issue ? Not reproduced

**Comment by hthetiot** [comment]
You need TURN server that 101 WebRTC. 
- https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/

**Comment by FredLuart** [comment]
@hthetiot Turn server is already managed by apiRTC

**Comment by hthetiot** [comment]
If it does not work in 4g but work in wifi it's 99% chance the users had TURN issue you don't agree?

**Comment by FredLuart** [comment]
It is a possibility. I am closing the issue as we don't have any feedback
